### PR TITLE
Done

### PR DESCRIPTION
**Pull request by aturkewi**

### CODE REVIEW

**Comment by aturkewi** [comment]
@AnnJohn I think you might want to un-merge this so it doesn't break the deploy. This was me just making a merge as a student to turn the lights. I don't think we want to be making changes to the deploys of the lab, only the canonical, right?

**Comment by PeterBell** [comment]
I'll fix @AnnJohn

**Comment by PeterBell** [comment]
Meh - can't force push to protected branch :(

OK, reverted and pushed Avidor's  3ab0aa1 commit - should be good

@avidor - mind looking and just checking I didn't mess anything up?

**Comment by aturkewi** [comment]
@PeterBell I think that looks good, but now it seems are deployer is broken :(
screen shot 2016-06-29 at 3 23 10 pm

Can we just destroy this deploy of the lab and then re-deploy?

**Comment by AnnJohn** [comment]
@PeterBell @aturkewi - will try now. going to delete this repo now

**Pull request merged**
